# Generated by Django 5.0.4 on 2024-05-03 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(max_length=256, verbose_name="место выполнения"),
                ),
                ("time_execute", models.TimeField(verbose_name="время для выполнения")),
                ("action", models.CharField(max_length=256, verbose_name="действие")),
                (
                    "is_nice",
                    models.BooleanField(
                        default=False, verbose_name="приятность привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("EVERY_DAY", "ED"),
                            ("EVERY_WEEK", "EW"),
                            ("EVERY_MONTH", "EM"),
                        ],
                        default="ED",
                    ),
                ),
                (
                    "reward",
                    models.CharField(max_length=256, verbose_name="вознаграждение"),
                ),
                (
                    "time_for_execute",
                    models.PositiveSmallIntegerField(
                        verbose_name="время на выполнение"
                    ),
                ),
                ("is_public", models.BooleanField(verbose_name="признак публичности")),
                (
                    "related_habit",
                    models.ManyToManyField(
                        to="habits.habit", verbose_name="связанная привычка"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="создатель",
                    ),
                ),
            ],
        ),
    ]
