# Generated by Django 5.0.4 on 2024-05-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_remove_habit_related_habit_alter_habit_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="action",
            field=models.CharField(
                default="новые действие", max_length=256, verbose_name="действие"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(default=True, verbose_name="признак публичности"),
        ),
        migrations.AlterField(
            model_name="habit",
            name="place",
            field=models.CharField(
                default="любое место", max_length=256, verbose_name="место выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                default="приятное вознаграждение",
                max_length=256,
                verbose_name="вознаграждение",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_execute",
            field=models.TimeField(
                default="00:00:00", verbose_name="время для выполнения"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_for_execute",
            field=models.PositiveSmallIntegerField(
                default="60", verbose_name="время на выполнение"
            ),
        ),
    ]
