# Generated by Django 5.0.4 on 2024-05-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0006_alter_habit_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="вознаграждение"
            ),
        ),
    ]
